name: albion-guild-manager

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: changeme
      POSTGRES_DB: agm
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
